//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.Enrolls = new HashSet<Enroll>();
        }
    
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public int Credit { get; set; }
        public string Instructor { get; set; }
        public int TotalSeats { get; set; }
        public int SeatsTaken { get; set; }
        public string CourseDesc { get; set; }
        public System.TimeSpan CourseTime { get; set; }
        public string CourseDays { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enroll> Enrolls { get; set; }
    }
}
