//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enroll
    {
        public string Grade { get; set; }
        public string UserUserId { get; set; }
        public int CourseCourseId { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual User User { get; set; }
    }
}
