//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Enrolls = new HashSet<Enroll>();
        }

        [RegularExpression("^[a-zA-Z0-9]+$")]
        [Required(ErrorMessage = "User Id is required")]
        public string UserId { get; set; }
        [DataType(DataType.Text)]
        [StringLength(30, MinimumLength = 3)]
        [Required(ErrorMessage = "First Name is required")]
        public string FirstName { get; set; }
        [DataType(DataType.Text)]
        [StringLength(30, MinimumLength = 3)]
        [Required(ErrorMessage = "Last Name is required")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Email Id is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string EmailID { get; set; }
        [Required(ErrorMessage = "Address is required")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Phone number required")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression("^[1-9][0-9]{9}$")]
        public Nullable<long> Phone { get; set; }
        [Required(ErrorMessage = "Gender is required")]
        public string Gender { get; set; }
        [StringLength(50, MinimumLength = 6)]
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Confirm Password is not match")]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "Department is required")]
        [RegularExpression("^[A-Za-z]*$")]
        [StringLength(50, MinimumLength = 2)]
        public string Department { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enroll> Enrolls { get; set; }
    }
}
